# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58030e3ccef7940a8ec19db4b259ca19ece44498b07303949a35d2f1924383ae6eabf3b1d2bd636563efce9aec7ec908f031ca5955d72247cb7f83447e7b3aac

test:
  secret_key_base: 9b3b0d7fb95136e7aac3fc0177e928f873f388357c873971f52823bcb9505906ac4b9287b1ffd0266f50873363796a508352aacd5e70b5565195d60ed2064b9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
